[book]
authors = ["Tanikella Tejaswi"]
language = "en"
src = "src"
title = "teja's notes"

[output.html]
default-theme = "auto"
mathjax-support = true
no-section-label = true

[output.html.fold]
enable = true

[output.html.playground]
copyable = true
line-numbers = true
